#!/bin/bash

function usage {
  echo "Usage: $0 [--indir] [--outdir] [--threads]"
  echo
  echo "Runs FastQC on all trimmed .fastq files in a specified input directory and writes .html reports to an output directory. Can run as many files in parallel as there are threads. This differs from part1_fastqc.sh in that it knows to skip the unpaired files (ending in U.fastq) generated by part2_trimmomatic_paired.sh"
  echo
  echo "  -i/--indir    input directory of fastq files"
  echo "  -o/--outdir   output directory for html reports"
  echo "  -t/--threads  number of threads"
  echo "  Version control: Nick Geraci July 27, 2017"
  echo
  exit 1
}

if [ "$1" == "-h" ]
then
  usage
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
  -i|--indir) # directory to read fastq files from
  INDIR="$2"
  shift
  ;;
  -o|--outdir) # directory for output html reports
  OUTDIR="$2"
  shift
  ;;
  -t|--threads) #number of threads
  THREADS="$2"
  shift
  ;;
  *)
  
  ;;
esac
shift
done

echo RUNNING FASTQC ON ALL .FASTQ FILES IN "${INDIR}" WITH "${THREADS}" THREADS
echo OUTPUT DIRECTORY = "${OUTDIR}"
INFILES="$INDIR/*P.fastq" # only run fastq on paired files
'/mnt/disks/disk-2/Tools/FastQC/fastqc' $INFILES --threads $THREADS --outdir $OUTDIR
